name = "contact-endpoint"
main = "src/worker.js"
compatibility_date = "2024-10-01"

[vars]
ALLOWED_ORIGIN = "https://othmane-elouardi.github.io"
FROM_EMAIL     = "website.onboarding@resend.dev"
TO_EMAIL       = "othmane@bu.edu"
